# Generated by Django 5.1 on 2024-10-10 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_productcomponent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_status', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Made'), (4, 'Delivered')], default=1, editable=False)),
                ('paid', models.IntegerField(choices=[(1, 'Not Paid'), (2, 'Fully Paid')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.client')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('item_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_status', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Made'), (4, 'Delivered')], default=1)),
                ('priority_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('completed', models.BooleanField(default=False)),
                ('option_values', models.ManyToManyField(blank=True, related_name='order_items', to='products.optionvalue')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
                ('product_finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.finishoption')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.component')),
                ('finish_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishoption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_component_finishes', to='orders.orderitem')),
            ],
            options={
                'verbose_name_plural': 'Component Finishes',
            },
        ),
    ]
