# Generated by Django 5.1 on 2024-09-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_value_orderitem_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
