# Generated by Django 5.1 on 2024-09-12 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
