# Generated by Django 5.1 on 2024-09-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_deposit_alter_order_discount_and_more'),
        ('products', '0007_alter_productcomponent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='option_values',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='products.optionvalue'),
        ),
    ]
