# Generated by Django 5.1 on 2024-09-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_deposit_alter_order_discount'),
        ('products', '0007_alter_productcomponent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='finish_options',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.finishoption'),
        ),
        migrations.CreateModel(
            name='ComponentFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.component')),
                ('finish_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishoption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_component_finishes', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OptionFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishoption')),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.optionvalue')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_option_finishes', to='orders.orderitem')),
            ],
        ),
    ]
