# Generated by Django 5.1 on 2024-09-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_options_remove_orderitem_finish_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentfinish',
            options={'verbose_name_plural': 'Component Finishes'},
        ),
        migrations.DeleteModel(
            name='OptionFinish',
        ),
    ]
