# Generated by Django 5.1 on 2024-10-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
