# Generated by Django 5.1 on 2024-10-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_archived'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE orders_orderitem DROP COLUMN archived;',
            reverse_sql='ALTER TABLE orders_orderitem ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;',
        ),
    ]
