# Generated by Django 5.1 on 2024-09-11 12:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcomponent_option_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='measurement_unit',
        ),
        migrations.CreateModel(
            name='ComponentPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='products.component')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
