# Generated by Django 5.1 on 2024-09-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_option_optionvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='finishes',
            field=models.ManyToManyField(blank=True, to='products.finish'),
        ),
    ]
