# Generated by Django 5.1 on 2024-09-12 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_componentpart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomponent',
            options={'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterField(
            model_name='component',
            name='supplier_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='componentpart',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
