# Generated by Django 5.1 on 2024-09-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productcomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomponent',
            options={},
        ),
    ]
