# Generated by Django 5.1 on 2024-09-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_finish_options_finishoption_finishoptionvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='components',
        ),
        migrations.RemoveField(
            model_name='productcomponent',
            name='product',
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='option_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.optionvalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finish',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finishoption',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finishoptionvalue',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
