# Generated by Django 5.1 on 2024-11-27 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productcomponent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
