# Generated by Django 5.1 on 2024-11-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productcomponent_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='unit_measurement',
            field=models.IntegerField(choices=[(1, 'm'), (2, 'kg'), (3, 'l'), (4, 'm2'), (5, 'm3'), (6, 'pc')], default=6),
        ),
    ]
