# Generated by Django 5.1 on 2024-09-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_finishoptionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='finishes',
            field=models.ManyToManyField(blank=True, to='products.finish'),
        ),
    ]
