# Generated by Django 5.1 on 2024-09-05 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_finish_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_components', to='products.product'),
        ),
        migrations.AddField(
            model_name='component',
            name='product_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_components', to='products.optionvalue'),
        ),
    ]
